---
title: "Exploratory Data Analysis with Python"
---


```{r, results="asis", eval = eval_num, echo = FALSE}
cat("<p style=\"background-color:#ffffff !important\">")
cat("`# Column indices of selected continuous variables:` ")
cat("<br>")  
indices <- which(colnames(df_code) %in% colnames(df_num))
indices <- indices-1
cat("`cols_continuous = ")
cat(paste0("[", paste(indices, collapse = ','), "]`"))
cat("</p>")
```

```{whites, eval = FALSE, echo = eval_num}
# Data frame of the continuous variables
df_num = df.iloc[:,cols_continuous]
```

```{r, results="asis", eval = eval_factor, echo = FALSE}
cat("<span style=\"background-color:white\">")
cat("`# Column indices of selected discrete variables:` ")
cat("<br>")  
indices <- which(colnames(df_code) %in% colnames(df_factor))
indices <- indices - 1
cat("`cols_discrete = ")
cat(paste0("[", paste(indices, collapse = ','), "]`"))
cat("</span>")
```

```{whites, eval = FALSE, echo = eval_factor}
# Data frame of the discrete variables
df_cat = df.iloc[:,cols_discrete]
```

```{whites, eval = FALSE, echo = eval_num}
# Continuous variables, descriptive statistics
df_num.sort_index(axis=1, inplace=True)
df_num_stats = df_num.describe()
df_num_stats = df_num_stats.transpose()
df_num_stats.drop(columns=['25%', '75%'], inplace=True)
df_num_stats.rename(columns={"count": "N Valid", "mean": "Mean", "50%": "Median", 
                             "std": "SD", "min": "Min", "max": "Max"}, inplace=True)
df_num_stats["N Obs"] = df_num.shape[0]
df_num_stats["N Missing"] = df_num.isna().sum()
df_num_stats["% Complete"] = (df_num_stats["N Valid"] / df_num_stats["N Obs"])*100
df_num_stats["N Unique"] = df_num.nunique(dropna=True)
df_num_stats["MAD"] = df_num.mad(axis=0)
df_num_stats["Skewness"] = df_num.skew(axis=0)
df_num_stats["Kurtosis"] = df_num.kurtosis(axis=0)
df_num_stats.loc[df_num_stats["Min"]>0,"CV"] = df_num_stats["SD"] / df_num_stats["Mean"]
df_num_stats = df_num_stats.round(2)
df_num_stats.loc[df_num_stats["Min"]<=0,"CV"] = ""

## Reorder columns to be similar to the output of the R app 
df_num_stats = df_num_stats.reindex(columns=["N Obs", "N Missing", "N Valid", 
                                             "% Complete", "N Unique", "Mean", 
                                             "SD", "Median", "MAD", "Min", "Max", 
                                             "Skewness", "Kurtosis", "CV"]) 

## Sort by variable name
df_num_stats.sort_index(inplace=True)

## Restrict size of characters of index 
cnames = np.array(df_num_stats.index).astype('str')
csize = min(np.max(np.char.str_len(cnames)),25)
df_num_stats.index = list(map(lambda x: x[0:csize], cnames))

## Output
print(tabulate(df_num_stats, headers='keys', tablefmt="simple"))
```


```{whites, eval = FALSE, echo = eval_num}
# Function for Histogram
def histo(ax, var, ylabel, xsize):
    sns.histplot(df_num.iloc[:,var], ax = ax, stat='density', 
                 color = '#2fa42d', kde = True, 
                 bins = len(np.unique(df_num.iloc[:,var]))//2)
    minvar = df_num.iloc[:,var].min()
    maxvar = df_num.iloc[:,var].max()
    xaxis = np.arange(minvar, maxvar, 0.001)
    fit_normal = stats.norm.pdf(xaxis, df_num.iloc[:,var].mean(), df_num.iloc[:,var].std())    
    ax.plot(xaxis, fit_normal, lw = 1, color = '#396e9f')
    ax.tick_params(axis='both', which='major', labelsize=10)
    ax.set_xlabel(df_num.columns[var], fontsize=xsize)
    ax.set_ylabel(ylabel)
    title = "Histogram of " + str(df_num.columns[var])
    ax.set_title(title)

# Large Histogram Plots
sns.set_style()
for var in range(df_num.shape[1]):
  fig, ax = plt.subplots(nrows = 1, ncols=1)
  histo(ax, var, "Density", 25)
  plt.show()
```


```{whites, eval = FALSE, echo = eval_num2}
# Function little helper to message the axs list to have correct length
def trim_axs(axs, N):
    axs = axs.flat
    for ax in axs[N:]:
        ax.remove()
    return axs[:N]

# Summary Histogram Plots
nrow = math.ceil(np.sqrt(df_num.shape[1]))
ncol = math.ceil(df_num.shape[1] / nrow)
fig, ax = plt.subplots(nrow, ncol)
fig.tight_layout(pad=3.0)
ax = trim_axs(ax, df_num.shape[1])
fig.subplots_adjust(hspace = 1)
for ax, var in zip(ax.flatten(), range(df_num.shape[1])):
   histo(ax, var, "", 8)
plt.show()
```


