---
title: "Exploratory Data Analysis with Python"
author: "Statsomat.com"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    highlight: NULL
classoption: landscape
params:
  data: NA
  filename: NA
  fencoding: NA
  decimal: NA
  enc_guessed: NA
  vars1: NA
  continuity: NA
header-includes:
   - \usepackage{xcolor}
   - \setmainfont[BoldFont=FiraSans-Bold, Extension=.otf]{FiraSans-Regular}
   - \usepackage{booktabs}
   - \usepackage{longtable}
   - \usepackage{float}
---


```{r child = 'report_kernel.Rmd', include = FALSE}
```


```{r include=FALSE}
if (exists("eval")) eval_code <- eval else eval_code <- FALSE
```

\pagebreak
 
\pagestyle{empty} 


<style>
pre.whites {
    background-color: #ffffff !important;
    border: 0;
}
</style>


```{css, echo=FALSE}
.evals {
  background-color: lightpink;
  border: 3px solid red;
  font-weight: bold;
}
```


```{r, results="asis", eval = eval_code, echo = FALSE}
cat("\n# Python Code ", fill=TRUE)
```


```{r, results="asis", eval = eval_code, echo = FALSE}
cat("If not already available, install Python and the packages defined further below. We recommend the Anaconda distribution (https://www.anaconda.com/) and Spyder as the IDE. Copy the code below, paste it carefully in a new Python file within Spyder. For a seamless copy \\& paste process, open the PDF report in a browser. Change the path to your data in the line ")
cat("`filepath = ...` ") 
cat("Run the code. Explore the results. ")
```


```{whites, eval = FALSE, echo = eval_code}
# Import required libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
from scipy import stats 
import math
import statsmodels.api as sm
from tabulate import tabulate
```


```{whites, eval = FALSE, echo = eval_code}
# Set console printing options 
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 20)
pd.set_option('display.width', 1000)
```


```{r, results="asis", eval = eval_code, echo = FALSE}
cat("`# Define the path to your data (please remark the forward slash)`")
cat("<br>")  
cat("`filepath = ")
cat(paste0("\"C:/",params$filename[1],"\"`"))
```

```{r, results="asis", eval = eval_code, echo = FALSE}
if (params$decimal == "auto"){
  cat("`# Upload the data`")
  cat("<br>")    
  
  # First read with dot 
  datainput1 <- fread(params$filename$datapath, header = "auto", sep = "auto", dec=".", encoding = "unknown", data.table = FALSE, na.strings = "")
  
  # Define colnames to finally decide for decimal character  
  colnames <- sapply(datainput1, function(col) is.numeric(col) & Negate(is.integer)(col))
  
  if (sum(colnames) == 0L){
    
    # Probably comma as decimal
    cat(paste0("`df = pd.read_csv(filepath, sep = None, decimal =\",\",  keep_default_na = False, na_values = \'\')`"))
    
  } else {
    cat(paste0("`df = pd.read_csv(filepath, sep = None, decimal =\".\",  keep_default_na = False, na_values = \'\')`"))
  }
  
} else {
  cat("\\# `Upload the data`")
  cat("\\newline ") 
  cat(paste0("`df = pd.read_csv(filepath, sep = None, decimal = \"", params$decimal,"\",  keep_default_na = False, na_values = \'\')`"))
  
}
```

```{r child = 'report_code_common.Rmd', eval = eval_code}
```
